/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import java.util.EventListener;

/**
 *
 * @author Kris
 */
public class Event extends javax.swing.JFrame {
    /**
     * Creates new form Event
     */
    public Event() {
        initComponents();
    }

    public void fijarController(EventListener controller){
        jBBack.addActionListener((ActionListener) controller);
        jBStar.addActionListener((ActionListener) controller);
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jBBack = new javax.swing.JButton();
        jBStar = new javax.swing.JButton();
        planoCartesiano = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jRadioDivide = new javax.swing.JRadioButton();
        jRadioProbabilistic = new javax.swing.JRadioButton();
        jRadioBackTracking = new javax.swing.JRadioButton();
        trips = new javax.swing.JLabel();
        totalTime = new javax.swing.JLabel();
        numberOfDronesByTheMoment = new javax.swing.JLabel();
        tripsByTheMoment = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        leftoverTime = new javax.swing.JLabel();
        fitTrips = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        record = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Drone Country");

        jBBack.setText("Back");

        jBStar.setText("Simulation");

        planoCartesiano.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout planoCartesianoLayout = new javax.swing.GroupLayout(planoCartesiano);
        planoCartesiano.setLayout(planoCartesianoLayout);
        planoCartesianoLayout.setHorizontalGroup(
            planoCartesianoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1578, Short.MAX_VALUE)
        );
        planoCartesianoLayout.setVerticalGroup(
            planoCartesianoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );

        jLabel3.setText("Type of algorithm:");

        buttonGroup1.add(jRadioDivide);
        jRadioDivide.setSelected(true);
        jRadioDivide.setText("Divide and counquer");

        buttonGroup1.add(jRadioProbabilistic);
        jRadioProbabilistic.setText("Probabilistic");

        buttonGroup1.add(jRadioBackTracking);
        jRadioBackTracking.setText("Backtracking");

        trips.setText("Trips sent:");

        totalTime.setText("Time to fit trips in miliseconds:");

        jLabel2.setText("Count:");

        jLabel4.setText("Leftover time in mili seconds:");

        record.setMaximumSize(new java.awt.Dimension(128, 661));
        jScrollPane1.setViewportView(record);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(203, 203, 203)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fitTrips, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(trips)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tripsByTheMoment, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(numberOfDronesByTheMoment, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(leftoverTime, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(875, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(33, 33, 33)
                        .addComponent(jRadioDivide)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioProbabilistic)
                        .addGap(32, 32, 32)
                        .addComponent(jRadioBackTracking)
                        .addGap(48, 48, 48)
                        .addComponent(jBStar)
                        .addGap(910, 910, 910)
                        .addComponent(jBBack))
                    .addComponent(planoCartesiano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(trips)
                            .addComponent(tripsByTheMoment, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalTime)
                            .addComponent(fitTrips, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(numberOfDronesByTheMoment, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(leftoverTime, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(planoCartesiano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBStar)
                            .addComponent(jBBack))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jRadioDivide)
                            .addComponent(jRadioProbabilistic)
                            .addComponent(jRadioBackTracking))
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JLabel fitTrips;
    public javax.swing.JButton jBBack;
    public javax.swing.JButton jBStar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JRadioButton jRadioBackTracking;
    public javax.swing.JRadioButton jRadioDivide;
    public javax.swing.JRadioButton jRadioProbabilistic;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel leftoverTime;
    public javax.swing.JLabel numberOfDronesByTheMoment;
    public javax.swing.JPanel planoCartesiano;
    public javax.swing.JTextPane record;
    private javax.swing.JLabel totalTime;
    private javax.swing.JLabel trips;
    public javax.swing.JLabel tripsByTheMoment;
    // End of variables declaration//GEN-END:variables
}
